### ISSUE TITLE
Neofetch

### ISSUE THREAD

**Issue by Onetryingtofollowthesunnah** [space-jesus/more-dracula#1]
Please add your neofetch config, it looks nice or if you can share a link of where the config is from? That would be really helpful :D

**Comment by space-jesus** [comment]
The neofetch config is in the config.conf file. [https://github.com/space-jesus/more-dracula/blob/main/config.conf](url)

**Comment by space-jesus** [comment]
https://github.com/space-jesus/more-dracula/blob/main/config.conf
